"""Nexora's public Python package."""

from importlib.metadata import PackageNotFoundError, version

from .background import BackgroundResult, BackgroundTasks
from .builtins import (
    BuiltinTools,
    ExecToolOptions,
    UrllibWebFetchTransport,
    WebFetchResponse,
    WebFetchSummarizer,
    WebFetchToolOptions,
    WebFetchTransport,
    builtin_tools,
)
from .contracts import (
    Agent,
    AgentDefinition,
    BaseMessage,
    CompactContext,
    DynamicTools,
    ModelErrorKind,
    ModelFailure,
    ModelFailureAction,
    OnModelFailure,
    PendingInput,
    SystemPromptSource,
    ToolCall,
    Tools,
)
from .engines.plain import react_loop
from .orchestration import (
    DurableRuntimeOrchestrator,
    RuntimeInputSession,
    RuntimeOrchestrationContext,
    RuntimeOrchestrationSession,
    RuntimeOrchestrator,
)
from .orchestrator import ModelFailurePolicy
from .prompts import PromptSection, SystemPrompt, prompt_section, volatile_prompt_section
from .providers import FallbackChatModel, ModelProvider, ProviderErrorKind
from .runtime import AgentRuntime, run
from .sandbox_remote import (
    HTTPResponse,
    HTTPTransport,
    RemoteSandboxClient,
    RemoteSandboxError,
    UrllibHTTPTransport,
)
from .skills import (
    DirectorySkillSource,
    Skill,
    SkillMetadata,
    SkillRegistry,
    SkillSource,
    SkillTools,
)
from .subagents import (
    Answering,
    Authority,
    FactoryAgent,
    HttpAgent,
    RunnerAgent,
    Subagent,
    Subagents,
)
from .tool_search import DeferredTools
from .workspace import (
    CommandResult,
    ContextualTools,
    ContinuousWorkspaceProvider,
    HostWorkspaceProvider,
    MemoryWorkspaceStateStore,
    ResolvedWorkspacePath,
    ResumableWorkspaceProvider,
    SandboxCommand,
    SandboxSessionState,
    SnapshotBackend,
    TarSnapshotBackend,
    ToolContext,
    WorkspaceAccessMode,
    WorkspaceDirEntry,
    WorkspaceFileStat,
    WorkspaceFS,
    WorkspaceProvider,
    WorkspaceSeed,
    WorkspaceSession,
    WorkspaceSnapshot,
    WorkspaceStateStore,
    WorkspaceViolation,
)

try:
    __version__ = version("nexora")
except PackageNotFoundError:  # pragma: no cover - source tree without installation
    __version__ = "0.0.0"

__all__ = [
    "Agent",
    "AgentDefinition",
    "AgentRuntime",
    "Answering",
    "Authority",
    "BackgroundResult",
    "BackgroundTasks",
    "BaseMessage",
    "BuiltinTools",
    "CommandResult",
    "CompactContext",
    "ContextualTools",
    "ContinuousWorkspaceProvider",
    "DeferredTools",
    "DirectorySkillSource",
    "DurableRuntimeOrchestrator",
    "DynamicTools",
    "ExecToolOptions",
    "FactoryAgent",
    "FallbackChatModel",
    "HTTPResponse",
    "HTTPTransport",
    "HostWorkspaceProvider",
    "HttpAgent",
    "MemoryWorkspaceStateStore",
    "ModelErrorKind",
    "ModelFailure",
    "ModelFailureAction",
    "ModelFailurePolicy",
    "ModelProvider",
    "OnModelFailure",
    "PendingInput",
    "PromptSection",
    "ProviderErrorKind",
    "RemoteSandboxClient",
    "RemoteSandboxError",
    "ResolvedWorkspacePath",
    "ResumableWorkspaceProvider",
    "RunnerAgent",
    "RuntimeInputSession",
    "RuntimeOrchestrationContext",
    "RuntimeOrchestrationSession",
    "RuntimeOrchestrator",
    "SandboxCommand",
    "SandboxSessionState",
    "Skill",
    "SkillMetadata",
    "SkillRegistry",
    "SkillSource",
    "SkillTools",
    "SnapshotBackend",
    "Subagent",
    "Subagents",
    "SystemPrompt",
    "SystemPromptSource",
    "TarSnapshotBackend",
    "ToolCall",
    "ToolContext",
    "Tools",
    "UrllibHTTPTransport",
    "UrllibWebFetchTransport",
    "WebFetchResponse",
    "WebFetchSummarizer",
    "WebFetchToolOptions",
    "WebFetchTransport",
    "WorkspaceAccessMode",
    "WorkspaceDirEntry",
    "WorkspaceFS",
    "WorkspaceFileStat",
    "WorkspaceProvider",
    "WorkspaceSeed",
    "WorkspaceSession",
    "WorkspaceSnapshot",
    "WorkspaceStateStore",
    "WorkspaceViolation",
    "__version__",
    "builtin_tools",
    "prompt_section",
    "react_loop",
    "run",
    "volatile_prompt_section",
]
